server:
  port: 8083

spring:
  application:
    name: auth-service
  boot:
    admin:
      client:
        url: http://127.0.0.1:8888 # Admin Server 地址
        instance:
          service-base-url: http://localhost:${server.port}
          discovery:
            enabled: false # 避开 LoadBalancer 拦截

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点给 Admin 监控
  endpoint:
    health:
      show-details: always