apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-server-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-server-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view  # K8s 内置的只读角色
subjects:
  - kind: ServiceAccount
    name: admin-server-sa
    namespace: default