apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort # 必須是 NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 #  固定一個端口，如 http://localhost:30000