apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - mysql-deployment.yaml
  - mysql-svc.yaml

# 自动生成 Secret：Kustomize 会自动读取明文并创建 K8s Secret 对象
secretGenerator:
  - name: mysql-pass
    literals:
      - password=your_complex_mysql_pwd  # 这里写明文，apply 时会自动加密
