spring:
  datasource:
    url: jdbc:mysql://://rm-xxxx.mysql.rds.aliyuncs.com # 生产用云数据库地址
  redis:
    cluster:
      nodes: # 生产环境可能是集群模式，结构与 base 不同
        - 192.168.1.1:6379
        - 192.168.1.2:6379