apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: prod

resources:
  - ../../base/apps/gateway-service 

configMapGenerator:
  - name: app-config-prod
    files:
      - application-prod.yaml

patches:
  - path: patch-mount-config.yaml # 增加挂载补丁

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  env: prod
  tier: application