apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 声明基础资源文件
resources:
  - deployment.yaml
  - service.yaml

# 2. (可选) 基础配置，如果所有环境都通用的 ConfigMap
# configMapGenerator:
#   - name: app-common-config
#     literals:
#       - LOG_LEVEL=info