server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          service-base-url: http://localhost:8081
  cloud:
    kubernetes:
      config:
        enabled: false
  h2:
    console:
      # Enables the H2 console
      enabled: true
      # Specifies the path to access the H2 console in your browser (e.g., http://localhost:8080/h2-console)
      path: /h2-console
  datasource:
    # JDBC URL for an in-memory H2 database named 'devdb'
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    # Default username for H2
    username: SA
    # Default password for H2 (often left blank or as 'password' for development)
    password: ''
    # Driver class name
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          jdbc:
            time_zone: UTC
      hibernate:
        ddl-auto: validate
      flyway:
        baseline-on-migrate: true