spring:
  boot:
    admin:
      client:
        url: http://spring-boot-admin
        instance:
          service-base-url: http://localhost:8082
  cloud:
    kubernetes:
      config:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            user-service:
              - host: localhost
                port: 8081
            spring-boot-admin:
              - host: localhost
                port: 8888
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: SA
    password: ''
    driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          jdbc:
            time_zone: UTC
      hibernate:
        ddl-auto: validate
      flyway:
        baseline-on-migrate: true

services:
  user-service:
    url: http://localhost:8081 # 指向本地启动的端口

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
