apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-service # 这里的名字要和 base 里的 metadata.name 一致
spec:
  template:
    spec:
      containers:
      - name: app # 这里的名字要和 base 里的 container name 一致
        # 1. 注入该服务特有的数据库连接信息
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/user_db?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "user_user"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: USER_USER_PASS
        # 2. 注入 Redis 密码
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        # 3. 为该服务定义资源限制 (根据业务压力调整)
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
