apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-service
spec:
  # 如果你想在开发环境通过宿主机 IP 访问，可以修改 type
  # type: NodePort 
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: 30001 # 仅在 type 为 NodePort 时有效
