apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server # 必须与 base 中的 metadata.name 一致
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
